# 1.You are given with a list of integer elements. Make a new list which will store square of elements of previous list.

In [3]:
def LSQR(lst):
    SQRlst = [i**2 for i in lst]
    return SQRlst

n = int(input("Enter number of elements: "))

lst = []
for i in range(n):
    lst.append(int(input()))
    
print("Square of entered list:",LSQR(lst))

Enter number of elements: 5
1
2
3
4
5
Square of entered list: [1, 4, 9, 16, 25]


# 2.From a list containing ints, strings and floats, make three lists to store them separately.

In [4]:
def Sep(mixlst):
    
    for i in mixlst:
        
        Ilst = [i for i in mixlst if isinstance(i,int)]
        
        Flst = [i for i in mixlst if isinstance(i,float)]
        
        Slst = [i for i in mixlst if isinstance(i, str)]
        
        Blst = [i for i in mixlst if isinstance(i, bool)]
        
    return Ilst,Flst,Slst,Blst

mixlist = [0,"bhavesh",0,"sawant",9.4,False,7,"vita",7.4,"dbda",True]

Int,Float,String,Bool = Sep(mixlist)

print(Int)
print(Float)
print(String)
print(Bool)

[0, 0, False, 7, True]
[9.4, 7.4]
['bhavesh', 'sawant', 'vita', 'dbda']
[False, True]


In [6]:
n = int(input("Enter number of rows: "))

for i in range(n):
    for p in range(1,i+2):
        print(p,end="")
        
    print()

Enter number of rows: 5
1
12
123
1234
12345


# 5.Write a Python program to check whether a given number is a narcissistic number or not For example, 371 is a narcissistic number; it has three digits,        and if we cube each digits  3^3 + 7^3 + 1^3 the sum is 371.                                  test case = 371,153,370,407,1634,8208,9474

In [7]:
def Narci(n,power):
    temp = n
    sum = 0
    while n != 0:
        r = n % 10
        sum += r**power
        n //= 10
    
    if sum == temp:
        return "Narcissistic Number"
    else:
        return "NOT Narcissistic Number"
    

n = int(input("Enter number: "))
power = len(str(n))
print(Narci(n,power))

Enter number: 8208
Narcissistic Number


# Addition of two matrices

In [8]:
import numpy as np

lst1 = []
lst2 = []



print("Enter values in first 3*3 Matrix: ")
for i in range(9):
    lst1.append(int(input()))
    
print("Enter values in second 3*3 Matrix: ")
for i in range(9):
    lst2.append(int(input()))


    
Mat1 = np.asarray(lst1)
Mat2 = np.asarray(lst2)
    
Mat1 = Mat1.reshape(3,3)
Mat2 = Mat2.reshape(3,3)

Add = Mat1 + Mat2

print("Addition of Mat1 and Mat2 is:","\n",Add)

Enter values in first 3*3 Matrix: 
1
2
3
4
5
6
7
8
9
Enter values in second 3*3 Matrix: 
1
2
3
4
5
6
7
8
9
Addition of Mat1 and Mat2 is: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
