In [1]:
import numpy

In [2]:
n=numpy.arange(5)
n

array([0, 1, 2, 3, 4])

In [3]:
type(n)

numpy.ndarray

In [4]:
print(n)

[0 1 2 3 4]


In [5]:
n.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [6]:
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
m=numpy.asarray([[123,234,678],[],[]])
m

array([list([123, 234, 678]), list([]), list([])], dtype=object)

In [11]:
print(m)

[list([123, 234, 678]) list([]) list([])]


In [12]:
type(m)

numpy.ndarray

In [13]:
a=[[5,6],[],[]]
a

[[5, 6], [], []]

In [14]:
print(a)
type(a)

[[5, 6], [], []]


list